deploy_production:
  stage: deploy
  image: kroniak/ssh-client
  environment: TESTNET-DEV
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$PRIVATEKEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh $USER@$SERVERHOST "cd /home/user0/project/zeetomic-core && docker-compose -f stack.yml down && git add . && git pull && docker-compose -f stack.yml up -d && notify.sh && exit"

  only:
    - master
