deploy_production:
  stage: deploy
  image: kroniak/ssh-client
  environment: TESTNET-DEV
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$PRIVATEKEY1" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - echo "$AWSKEY" > ~/.ssh/zeetomic-key.pem
    - chmod 400 ~/.ssh/zeetomic-key.pem
    #adding key.pem to host
    #PRD
    #- ssh -i "~/.ssh/zeetomic-key.pem" ec2-user@ec2-54-255-208-86.ap-southeast-1.compute.amazonaws.com "cd /home/ec2-user/zeetomic-core && docker-compose -f stack.yml down && git add . && git pull && docker-compose -f stack.yml up -d && ./notify.sh && exit"
    #TEST
    - ssh -i "~/.ssh/zeetomic-key.pem" ec2-user@ec2-52-221-187-194.ap-southeast-1.compute.amazonaws.com "cd /home/ec2-user/zeetomic-core && docker-compose -f stack.yml down && git add . && git pull && docker-compose -f stack.yml up -d && ./notify.sh && exit"
  
  only:
    - master
