deploy_production:
  stage: deploy
  image: kroniak/ssh-client
  environment: TESTNET-DEV
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$PRIVATEKEY1" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - echo "$AWSKEY" > ~/.ssh/zeetomic-key.pem
    - chmod 400 ~/.ssh/zeetomic-key.pem
    - cat ~/.ssh/id_ed25519
    - cat ~/.ssh/zeetomic-key.pem
    #- ssh $USER@$SERVERHOST "cd /home/user0/project/zeetomic-core && docker-compose -f stack.yml down && git add . && git pull && docker-compose -f stack.yml up -d && ./notify.sh && exit"
    #- ssh -i "~/.ssh/zeetomic-key.pem" ec2-user@ec2-54-255-208-86.ap-southeast-1.compute.amazonaws.com "ls && exit"

  only:
    - master
