-- :name create-branches-table :! 
CREATE TABLE IF NOT EXISTS BRANCHES (
    ID VARCHAR (36) PRIMARY KEY,
    MERCHANTS_ID VARCHAR (36),
    BRANCHES_NAME VARCHAR (50) UNIQUE,
    ADDRESS TEXT,
    REWARD_RATES NUMERIC,
    ASSET_CODE VARCHAR (4),
    MINIMUM_SPEND NUMERIC,
    APPROVAL_CODE VARCHAR (6),
    LOGO_URI    TEXT,
    IS_ACTIVE BOOLEAN NOT NULL default TRUE,
    CREATED_AT timestamp NOT NULL default current_timestamp,
    UPDATED_AT timestamp,
    CREATED_BY VARCHAR (36),
    GRANTED_FOR VARCHAR (36)
)

-- :name drop-branches-table :!
DROP TABLE IF EXISTS BRANCHES

-- :name add-branches :! :n 
INSERT INTO BRANCHES (ID, MERCHANTS_ID, BRANCHES_NAME, ADDRESS, REWARD_RATES, ASSET_CODE, MINIMUM_SPEND, APPROVAL_CODE, LOGO_URI, CREATED_BY)
VALUES (:ID, :MERCHANTS_ID, :BRANCHES_NAME, :ADDRESS, :REWARD_RATES, :ASSET_CODE, :MINIMUM_SPEND, :APPROVAL_CODE, :LOGO_URI, :CREATED_BY)

-- :name update-branches :! :n
UPDATE BRANCHES
SET ADDRESS         = :ADDRESS,
    REWARD_RATES    = :REWARD_RATES,
    ASSET_CODE      = :ASSET_CODE,
    MINIMUM_SPEND   = :MINIMUM_SPEND,
    APPROVAL_CODE   = :APPROVAL_CODE,
    LOGO_URI        = :LOGO_URI,
    IS_ACTIVE       = :IS_ACTIVE
WHERE ID = :ID

--:name get-all-branches :? :*
SELECT * FROM BRANCHES

-- :name get-branches-by-name :? :1
SELECT * FROM BRANCHES
WHERE BRANCHES_NAME = :BRANCHES_NAME

--:name list-all-branches :? :*
SELECT BRANCHES_NAME,
        ADDRESS,
        REWARD_RATES,
        ASSET_CODE,
        MINIMUM_SPEND,
        LOGO_URI,
        IS_ACTIVE
 FROM BRANCHES

 --:name list-branches-by-granted :? :1
SELECT BRANCHES_NAME,
        ADDRESS,
        REWARD_RATES,
        ASSET_CODE,
        MINIMUM_SPEND,
        LOGO_URI,
        IS_ACTIVE
 FROM BRANCHES
 WHERE GRANTED_FOR = :GRANTED_FOR

 -- ALTER TABLE branches
 -- ADD GRANTED_FOR VARCHAR (36); 
 -- :name granted-to :! :n
UPDATE BRANCHES
SET GRANTED_FOR         = :GRANTED_FOR
WHERE BRANCHES_NAME = :BRANCHES_NAME