-- :name create-documents-table :! 
CREATE TABLE IF NOT EXISTS DOCUMENTS (
    ID VARCHAR (36) PRIMARY KEY,
    DOCUMENTS_NO VARCHAR (50),
    DOCUMENTTYPE_ID VARCHAR (50),
    DOCUMENT_URI TEXT NOT NULL,
    FACE_URI TEXT NOT NULL,
    ISSUE_DATE TEXT NOT NULL,
    EXPIRE_DATE TEXT NOT NULL,
    CREATED_AT timestamp NOT NULL default current_timestamp,
    UPDATED_AT timestamp,
    CREATED_BY VARCHAR (36),
    UPDATED_BY VARCHAR (36)
)

-- :name drop-documents-table :!
DROP TABLE IF EXISTS DOCUMENTS

-- :name get-all-documents :? :*
SELECT * FROM DOCUMENTS

-- :name set-documents :! :n 
-- :doc Create at 28APR2020
-- :doc Modified at 28APR2020 by Saing 
INSERT INTO DOCUMENTS (ID, DOCUMENTS_NO, DOCUMENTTYPE_ID, DOCUMENT_URI, FACE_URI, ISSUE_DATE, EXPIRE_DATE, CREATED_BY)
VALUES (:ID, :DOCUMENTS_NO, :DOCUMENTTYPE_ID, :DOCUMENT_URI, :FACE_URI, :ISSUE_DATE, :EXPIRE_DATE, :CREATED_BY)


